chore(): improve docs
baloise/design-system pull request #1118
Opened 2023-11-09 13:55 UTC by mladenplaninicic

2023-11-09 13:56 UTC, incubator-tekton commented
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

2023-12-04 14:06 UTC, hirsch88 requested changes

2023-12-04 14:06 UTC, hirsch88 commented on docs/stories/components/bal-divider/bal-divider.stories.ts
> +    ...withDefaultContent(),
- [x] remove withDefaultContent

2023-12-04 14:06 UTC, hirsch88 commented on docs/stories/components/bal-divider/bal-divider.stories.ts
>      ...withContent(),
- [x] remove withContent

2023-12-05 08:17 UTC, hirsch88 approved these changes

2023-12-05 08:17 UTC, merged