✨ feat(form): horizontal layout for label and controls
baloise/design-system pull request #1169
Opened 2023-11-30 14:54 UTC by mladenplaninicic

2023-11-30 14:54 UTC, incubator-tekton commented
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

2023-12-04 09:02 UTC, hirsch88 requested changes

2023-12-04 09:02 UTC, hirsch88 commented on packages/components/src/components/bal-field/bal-field.vars.sass
> +  --bal-field-label-horizontal-width: 33%
use `33.3333`

2023-12-04 09:02 UTC, hirsch88 commented on test/cypress/snapshots/base/visual/bal-field.visual.cy.ts/horizontal-alignment-desktop.png
- [x] add visual test for long labels and message

2023-12-04 09:04 UTC, hirsch88 commented on packages/components/src/components.d.ts
> +        "horizontalAlignment"?: boolean;
- [x] rename to horizontal

2023-12-04 11:33 UTC, hirsch88 requested changes

2023-12-04 11:33 UTC, hirsch88 commented on packages/components/src/components/bal-field/bal-field.sass
> +    margin-left: calc(var(--bal-field-label-horizontal-width) + (var(--bal-field-label-column-gap) * 2) + 18px)
what is 18px?

2023-12-04 11:33 UTC, hirsch88 commented on .changeset/slow-parrots-argue.md
> +---
- [x] add the documentation to storybook

2023-12-05 09:18 UTC, hirsch88 approved these changes

2023-12-05 12:26 UTC, merged