Feature add hint color balheading
baloise/design-system pull request #392
Opened 2021-11-12 10:36 UTC by abeerance

Closes #

Add hint color for BalHeading by adding new component colortype

#### Changelog

**New**

- Added new colortype hint

**Changed**

- Added new colortype in BalHeading

**Removed**

- None

2021-11-12 10:36 UTC, incubator-tekton commented
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

2021-11-18 07:38 UTC, hirsch88 requested changes
Thanks a lot for you pr. I added some comments for approvment.

2021-11-18 07:38 UTC, hirsch88 commented on packages/components/src/components/bal-file-upload/bal-file-upload.scss
> +  background: $red;
Should this really be red?

2021-11-18 07:38 UTC, hirsch88 commented on packages/components/src/components/bal-heading/index.html
> +        <bal-heading color="hint" level="h4" space="none">Hint</bal-heading>
Instead of adding hint we could change info to that hint color, because default is already blue.

2021-11-22 13:11 UTC, sladomic commented
will be done in v2.0.1 or v2.0.2 by changing the "info" color to the desired color (hint)

2021-11-23 08:44 UTC, hirsch88 commented
Will be done in https://github.com/baloise/design-system/pull/401

2021-11-23 08:44 UTC, closed without merging