Contract numbers input
baloise/design-system pull request #537
Opened 2022-03-05 19:06 UTC by nobilo

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-03-05 19:07 UTC, incubator-tekton commented
:rocket: Welcome to Baloise ChatOps based GitOps Bot :tada:
                                
    - If you want to enable preview environments for this PullRequest, comment with `/preview`. 
    - If you want to disable the preview environment for this PR, comment with `/undeploy`. 
    - If you need help or want to see the docs, comment with `/help`. 
                                
    Make sure to refresh this page after submitting a command.
    Preview environments can be redeployed automatically if you enable the webhook for updates to the source branch. :new:
    
    Have fun building awesome apps! :hammer:  :whale2:  :truck:  :ship:

2022-03-22 06:26 UTC, hirsch88 requested changes

2022-03-22 06:26 UTC, hirsch88 commented on packages/components/src/components/form/bal-input/bal-input.tsx
> +   // */
could you remove the last two slashes

2022-03-22 06:26 UTC, hirsch88 commented on packages/components/src/components/form/bal-input/bal-input.tsx
> +  private formatClaim(value: string): string {
could we move that in to a util file, so that we have unit tests for it?

2022-03-22 06:26 UTC, hirsch88 commented on packages/components/src/components/form/bal-input/bal-input.tsx
> +const MAX_LENGTH_CONTRACT_NUMBER = 9
put the const also into the mask.util file

2022-03-30 08:39 UTC, hirsch88 approved these changes

2022-03-30 09:03 UTC, merged